[tools]
claude-code = "latest"
fd = "latest"
ffmpeg = "latest"
gh = "latest"
glow = "latest"
jq = "latest"
node = "latest"
oh-my-posh = "latest"
pipx = "latest"
prettier = "latest"
python = "latest"
rg = "latest"
uv = "latest"

[settings]
install_before = "7d" # Preventing supply-chain attack https://mise.jdx.dev/tips-and-tricks.html#minimum-release-age

[settings.aqua]
github_attestations = false # https://github.com/jdx/mise/discussions/8142
