# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

final_space: true
version: 2.0
blocks:
- type: prompt
  alignment: left
  segments:
  - type: status
    style: plain
    foreground: "#FF0000"
    template: "{{.String}}"
  - type: python
    style: plain
    foreground: "#80a0ff"
    properties:
      fetch_version: false
    template: " {{.Venv}}"
  - type: path
    style: plain
    foreground: "#56B6C2"
    properties:
      style: full
    template: " {{.Path}}"
  - type: git
    style: plain
    foreground: "#6871FF"
    properties:
      branch_icon: ""
      fetch_status: true
    templates:
    - " {{.HEAD}}"
    - "{{if .BranchStatus}}{{.BranchStatus}}{{end}}"
    - "{{if .Working.Changed}}<#FFFF00>{{end}}"
    - "{{if .Staging.Changed}}<#ADFF2F>{{end}}"
  - type: root
    style: plain
    foreground: "#ffff66"
    template: " "
