# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

blocks:
- alignment: left
  segments:
  - foreground: "#98C379"
    foreground_templates:
    - "{{ if gt .Code 0 }}#FF0000{{ end }}"
    properties:
      always_enabled: true
      display_exit_code: true
    style: plain
    template: ➜{{ if gt .Code 0 }}\uf00d {{ .Meaning }}{{ else }}\uf42e{{ end }}
    type: exit
  - foreground: "#80a0ff"
    properties:
      display_default: false
      display_mode: environment
      fetch_version: false
    style: plain
    template:  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}
    type: python
  - foreground: "#56B6C2"
    properties:
      style: short
    style: plain
    template:  {{ .Path }}
    type: path
  - foreground: "#6871FF"
    properties:
      branch_icon: ""
      cherry_pick_icon: ""
      commit_icon: ""
      fetch_status: true
      merge_icon: ""
      rebase_icon: ""
      tag_icon: ""
    style: plain
    template: " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 <#FFFF00>{{ .Working.String }}</>{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }}{{ end }}{{ if .Staging.Changed }} \uf046 <#ADFF2F>{{ .Staging.String }}</>{{ end }}"
    type: git
  - foreground: "#ffff66"
    style: plain
    template:  \uf0e7
    type: root
  type: prompt
final_space: true
version: 2.0

