#!/usr/bin/env bash

# Turns on roku captions

set -o errexit
set -o nounset
set -o pipefail

if [[ $# -ne 0 ]]; then
  >&2 echo "USAGE: roku-capoff"
  exit 1
fi

echo 'WIP TODO need to map current closed-caption-mode into up or down to toggle it!'
exit 1

ROKU="192.168.86.208:8060"
curl -s "http://$ROKU/query/device-info" \
  | sed -n 's:.*<closed-caption-mode>\(.*\)</closed-caption-mode>.*:\1:p'

roku info
roku down
roku down
roku down
roku select # Accessibility and Language
roku select # Closed captioning
roku up # Captions on -> off
roku select
roku info


