#!/usr/bin/env uv run
"""Transcribe a stereo WAV file with speaker labels (left=Me, right=You).
#ai-slop generated by Cursor

Currently supports only Apple Silicon. Recommendations for others:
- Windows + GTX 1060: Best option for cost/performance. Use faster-whisper with int8 quantization.
- Linux cloud CPU-only: Only if you can accept lower accuracy (tiny/base models) or very long wait times.
- Linux cloud GPU: Only if you need cloud processing and can afford GPU instances (~$0.50+/hour).
"""

# /// script
# dependencies = [
#     "mlx-whisper",
# ]
# ///

import argparse
import logging
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import mlx_whisper

logger = logging.getLogger(__name__)

# Config
SPEAKER_LEFT = "You"
SPEAKER_RIGHT = "Me"

# If you get "Repository Not Found / Please make sure you specified the correct..." you have a typo in the model name
WHISPER_MODEL = "mlx-community/whisper-large-v3-mlx"


@dataclass(frozen=True)
class Segment:
  """A transcribed segment with timing and speaker info."""

  start: float
  end: float
  text: str
  speaker: str = ""


def split_stereo(input_wav: Path, temp_dir: Path, preview_seconds: int | None = None) -> tuple[Path, Path]:
  """Split stereo WAV into left and right channels using ffmpeg."""
  left_wav = temp_dir / "left.wav"
  right_wav = temp_dir / "right.wav"

  cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error"]
  if preview_seconds is not None:
    # -t before -i limits how much input ffmpeg reads, so it doesn't decode the whole file
    cmd += ["-t", str(preview_seconds)]
  cmd += [
    "-i", str(input_wav),
    "-filter_complex",
    "channelsplit=channel_layout=stereo[left][right]",
    "-map", "[left]", str(left_wav),
    "-map", "[right]", str(right_wav),
  ]
  logger.debug("Running: %s", " ".join(cmd))
  subprocess.run(cmd, check=True, timeout=60)
  logger.info("Split stereo into %s and %s", left_wav.name, right_wav.name)
  return left_wav, right_wav


def transcribe_audio(audio_path: Path, speaker: str) -> list[Segment]:
  """Transcribe audio file using mlx-whisper and return segments."""
  logger.info("Transcribing %s...", audio_path.name)
  result = mlx_whisper.transcribe(
    str(audio_path),
    path_or_hf_repo=WHISPER_MODEL,
    language="en",
    word_timestamps=True,
    verbose=False,
    # Prevent hallucination loops
    condition_on_previous_text=False,  # Don't let previous output influence next segment
    compression_ratio_threshold=2.4,  # Skip segments with repetitive text
    no_speech_threshold=0.6,  # Skip silent segments
    logprob_threshold=-1.0,  # Skip low-confidence outputs (default -1.0)
    hallucination_silence_threshold=2.0,  # Skip if >2s trailing silence detected
  )

  segments = []
  for seg in result.get("segments", []):
    start = float(seg.get("start", 0.0))
    end = float(seg.get("end", start))
    text = seg.get("text", "").strip()
    segments.append(Segment(start=start, end=end, text=text, speaker=speaker))

  logger.info("Got %d segments from %s", len(segments), audio_path.name)
  return segments


def main() -> None:
  parser = argparse.ArgumentParser(description="Transcribe stereo WAV with speaker labels")
  parser.add_argument("input_wav", type=Path, help="Input stereo WAV file")
  parser.add_argument(
    "--preview",
    type=int,
    metavar="SECONDS",
    help="Transcribe only the first N seconds and print to stdout instead of writing a file",
  )
  parser.add_argument(
    "-v", "--verbose", action="store_true", help="Verbose output"
  )
  args = parser.parse_args()

  logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    # Keep root (and noisy deps like mlx) at WARNING
    level=logging.WARNING,
    datefmt="%Y-%m-%d %H:%M:%S",
  )
  logger.setLevel(logging.DEBUG if args.verbose else logging.INFO)

  input_wav: Path = args.input_wav
  if not input_wav.exists():
    sys.exit(f"Input file not found: {input_wav}")

  output_path = input_wav.with_suffix(".md")

  temp_dir = Path(tempfile.mkdtemp(prefix="stereo_transcribe_"))
  try:
    left_wav, right_wav = split_stereo(input_wav, temp_dir, preview_seconds=args.preview)

    # Transcribe both channels with speaker labels
    left_segments = transcribe_audio(left_wav, speaker=SPEAKER_LEFT)
    right_segments = transcribe_audio(right_wav, speaker=SPEAKER_RIGHT)

    # Merge and sort by time
    combined = sorted(left_segments + right_segments, key=lambda s: s.start)

    # Write transcript with timestamps: [MM:SS] Speaker: Text
    longest_speaker = max(len(seg.speaker) for seg in combined)
    out_lines = []
    for seg in combined:
      text = seg.text.strip()
      minutes = int(seg.start // 60)
      seconds = int(seg.start % 60)
      timestamp = f"[{minutes:02d}:{seconds:02d}]"

      out_lines.append(f"{timestamp} {seg.speaker + ":":{longest_speaker+1}} {text}")

    if args.preview is not None:
      print("\n".join(out_lines))
    else:
      output_path.write_text("\n".join(out_lines))
      logger.info("Wrote %d lines to %s", len(out_lines), output_path)
  finally:
    # Cleanup temp directory
    # TODO shutil.rmtree(temp_dir, ignore_errors=True)
    logger.info("Cleaned up temp files")


if __name__ == "__main__":
  main()
