#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

displayplacer "id:5BC69910-9926-4578-B587-CF7353C50E00 res:2560x1440 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:3CC46B27-B145-4161-A873-733CF414F96C res:1440x2560 hz:60 color_depth:8 scaling:off origin:(2560,-620) degree:90"

>&2 echo wait a bit...
