tap "bwilczynski/tap"
tap "hashicorp/tap"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "homeport/tap"
tap "hudochenkov/sshpass"
tap "isen-ng/dotnet-sdk-versions"
tap "jakehilborn/jakehilborn"
tap "jandedobbeleer/oh-my-posh"
# ARP scanning and fingerprinting tool
brew "arp-scan"
# Official Amazon AWS command-line interface
brew "awscli"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# Convert text between DOS, UNIX, and Mac formats
brew "dos2unix"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# GNU compiler collection
brew "gcc"
# Command-line tools for fly.io services
brew "flyctl"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# GNU awk utility
brew "gawk"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Small utility that generates Go code from any file
brew "go-bindata"
# Fast linters runner for Go
brew "golangci-lint"
# Modern, extensible Python project management
brew "hatch"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Command-line interface for JFrog products
brew "jfrog-cli"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Development kit for the Java programming language
brew "openjdk"
# Java-based project management
brew "maven"
# Cross platform, open source .NET development framework
brew "mono"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Platform built on V8 to build network applications
brew "node"
# Prompt theme engine for any shell
brew "oh-my-posh"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Show ps output as a tree
brew "pstree"
# Python version management
brew "pyenv"
# Cross-platform application and UI framework
brew "qt"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# ISO/Edinburgh-style Prolog interpreter
brew "swi-prolog"
# User interface to the TELNET protocol
brew "telnet"
# Image processing library
brew "vips"
# JavaScript package manager
brew "yarn"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Strava Command-Line Tools
brew "bwilczynski/tap/strava-cli"
# Terraform
brew "hashicorp/tap/terraform"
# Vault
brew "hashicorp/tap/vault"
# δyƒƒ /ˈdʏf/ - A diff tool for YAML files, and sometimes JSON
brew "homeport/tap/dyff"
brew "hudochenkov/sshpass/sshpass"
# macOS command line utility to configure multi-display resolutions and arrangements. Essentially XRandR for macOS.
brew "jakehilborn/jakehilborn/displayplacer"
# Command-line interface for 1Password
cask "1password-cli"
# Enable Windows-like alt-tab
cask "alt-tab"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker"
# Developer platform
cask "dotnet-sdk"
# This cask follows releases from https://github.com/dotnet/core/tree/master
cask "dotnet-sdk3-1-400"
# This cask follows releases from https://github.com/dotnet/core/tree/master
cask "dotnet-sdk5-0-400"
# This cask follows releases from https://github.com/dotnet/core/tree/master
cask "dotnet-sdk6-0-400"
# This cask follows releases from https://github.com/dotnet/core/tree/master
cask "dotnet-sdk7-0-400"
# This cask follows releases from https://github.com/dotnet/core/tree/master
cask "dotnet-sdk8"
# This cask follows releases from https://github.com/dotnet/core/tree/master
cask "dotnet-sdk8-0-400"
cask "font-meslo-lg-nerd-font"
# Web browser
cask "google-chrome"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Client for the Google Drive storage service
cask "google-drive"
# Avalonia-based .NET decompiler
cask "ilspy"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Extensible editor for OpenStreetMap
cask "josm"
# Keyboard customiser
cask "karabiner-elements"
# Shows the next meeting in the menu bar
cask "meetingbar"
# Set of CPU, memory, disk, and network monitoring tools
cask "menumeters"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Finder Toolbar app to open the current directory in Editor
cask "openineditor-lite"
# Finder Toolbar app to open the current directory in Terminal
cask "openinterminal-lite"
# Desktop virtualization software
cask "parallels"
# Command-line shell and scripting language
cask "powershell"
# Allows users with an iSight (or compatible) camera to read QR codes
cask "qr-journal"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Time optimising application
cask "rescuetime"
# Video game digital distribution service
cask "steam"
# Enable Windows-like program quitting when all windows are closed
cask "swift-quit"
# Open-source code editor
cask "visual-studio-code"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Rust-based terminal
cask "warp"
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "Numbers", id: 409203825
mas "Online Check", id: 6504709660
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
