tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "isen-ng/dotnet-sdk-versions"
tap "jakehilborn/jakehilborn"
# Official Amazon AWS command-line interface
brew "awscli"
# Core application library for C
brew "glib"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# Convert text between DOS, UNIX, and Mac formats
brew "dos2unix"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# GNU awk utility
brew "gawk"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Small utility that generates Go code from any file
brew "go-bindata"
# Simple jira command-line client in Go
brew "go-jira"
# Fast linters runner for Go
brew "golangci-lint"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Command-line interface for JFrog products
brew "jfrog-cli"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Java-based project management
brew "maven"
# Cross platform, open source .NET development framework
brew "mono"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Prompt theme engine for any shell
brew "oh-my-posh"
# Development kit for the Java programming language
brew "openjdk@11"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Show ps output as a tree
brew "pstree"
# Python version management
brew "pyenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Cross-platform application and UI framework
brew "qt"
brew "sshpass"
# User interface to the TELNET protocol
brew "telnet"
# JavaScript package manager
brew "yarn"
# Vault
brew "hashicorp/tap/vault"
# macOS command line utility to configure multi-display resolutions and arrangements. Essentially XRandR for macOS.
brew "jakehilborn/jakehilborn/displayplacer"
# Command-line interface for 1Password
cask "1password-cli"
# Enable Windows-like alt-tab
cask "alt-tab"
# App to build and share containerized applications and microservices
cask "docker"
# Developer platform
cask "dotnet-sdk"
# This cask follows releases from https://github.com/dotnet/core/tree/master
cask "dotnet-sdk3-1-400"
# This cask follows releases from https://github.com/dotnet/core/tree/master
cask "dotnet-sdk5-0-400"
cask "font-meslo-for-powerline"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Avalonia-based .NET decompiler
cask "ilspy"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Extensible editor for OpenStreetMap
cask "josm"
# Keyboard customizer
cask "karabiner-elements"
# Shows the next meeting in the menu bar
cask "meetingbar"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Finder Toolbar app to open the current directory in Editor
cask "openineditor-lite"
# Finder Toolbar app to open the current directory in Terminal
cask "openinterminal-lite"
# Command-line shell and scripting language
cask "powershell"
# Allows users with an iSight (or compatible) camera to read QR codes
cask "qr-journal"
# Video game digital distribution service
cask "steam"
# Remote desktop application focusing on security
cask "vnc-viewer"
mas "Keynote", id: 409183694
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "Pages", id: 409201541
mas "Pages", id: 409201541
mas "Tomito", id: 1526042938
mas "Xcode", id: 497799835
